import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProtectLogin from "@/components/auth/ProtectLogin";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="antialiased bg-[#F5F7FA] min-h-screen w-full">
        <ProtectLogin>{children}</ProtectLogin>
      </body>
    </html>
  );
}
